#pragma once
// Auto-generated by PUKE. Do not edit.

#define PUKE_CUSTOM_NAMESPACE puke::custom_cpp_radio_selection
#define PUKE_CUSTOM_TYPE_ID "custom_cpp_radio_selection"
#include "radio_selection.h"
#undef PUKE_CUSTOM_TYPE_ID
#undef PUKE_CUSTOM_NAMESPACE

static ModuleInstanceBase* create_radio_selection()
{
    return new TemplateInstance<puke::custom_cpp_radio_selection::Processor>();
}

static const PukeCustomNodeMetadata* get_meta_radio_selection()
{
    return puke::custom_cpp_radio_selection::getCustomNodeMetadata();
}

static const TemplateEntry kCustomTemplates[] =
{
    { puke::custom_cpp_radio_selection::kNodeTypeId, &get_meta_radio_selection, &create_radio_selection },
};

static const int kCustomTemplateCount = (int) (sizeof (kCustomTemplates) / sizeof (kCustomTemplates[0]));
